* Terminal
** Setting default shell to bash
#+begin_src emacs-lisp
  (defvar my-term-shell "/bin/bash")
  (defadvice ansi-term (before force-bash)
    (interactive (list my-term-shell)))
  (ad-activate 'ansi-term)
#+end_src
** Hotkey
#+begin_src emacs-lisp
  (global-set-key (kbd "<s-return>") 'ansi-term)
#+end_src
* Disabled defaults
** Backup files
#+begin_src emacs-lisp
  (setq make-backup-file nil)
  (setq auto-save-default nil)
#+end_src
** Disable bars
#+begin_src emacs-lisp
  (tool-bar-mode -1)
  (menu-bar-mode -1)
#+end_src
** Bell
#+begin_src emacs-lisp
  (setq ring-bell-function 'ignore)
#+end_src
** Startup Message
#+begin_src emacs-lisp
  (setq inhibit-startup-message t)
#+end_src
* Shorter Y/N
#+begin_src emacs-lisp
  (defalias 'yes-or-no-p 'y-or-n-p)
#+end_src
* Panning
#+begin_src emacs-lisp
  (setq scroll-conservatively 100)
#+end_src
* Line highlight
#+begin_src emacs-lisp
  (when window-system (global-hl-line-mode t))
#+end_src
* Pretty Symbols
#+begin_src emacs-lisp
  (when window-system (global-prettify-symbols-mode t))
#+end_src
* Key help
#+begin_src emacs-lisp
  (use-package which-key
    :ensure t
    :init
    (which-key-mode))
#+end_src
* Cosmetics
** Line beacon
#+begin_src emacs-lisp
  (use-package beacon
    :ensure t
    :init
    (beacon-mode 1))
#+end_src
* Org
** Org Bullets
#+begin_src emacs-lisp
  (use-package org-bullets
    :ensure t
    :config
    (add-hook 'org-mode-hook (lambda() (org-bullets-mode))))
#+end_src
** Org Tempo
#+begin_src emacs-lisp
  (require 'org-tempo)
#+end_src
** emacs-lisp source block
#+begin_src emacs-lisp
  (add-to-list 'org-structure-template-alist '("el" . "src emacs-lisp"))
#+end_src
* IDO
** Enable IDO mode
#+begin_src emacs-lisp
  (setq ido-enable-flex-matching nil)
  (setq ido-create-new-buffer 'always)
  (setq ido-everywhere t)
  (ido-mode 1)
#+end_src

** IDO-Vertical
#+begin_src emacs-lisp
  (use-package ido-vertical-mode
    :ensure t
    :init
    (ido-vertical-mode 1))
  (setq ido-vertical-define-keys 'C-n-and-C-p-only)
#+end_src

** smex
#+begin_src emacs-lisp
  (use-package smex
    :ensure t
    :init (smex-initialize)
    :bind
    ("M-x" . smex))
#+end_src

** switch buffer
#+begin_src emacs-lisp
  (global-set-key (kbd "C-x C-b") 'ido-switch-buffer)
#+end_src
* Buffers
** Enable ibuffer
#+begin_src emacs-lisp
  (global-set-key (kbd "C-x b") 'ibuffer)
#+end_src
** Always kill current buffer
#+begin_src emacs-lisp
  (defun kill-curr-buffer ()
    (interactive)
    (kill-buffer (current-buffer)))
  (global-set-key (kbd "C-x k") 'kill-curr-buffer)
#+end_src
* avy
#+begin_src emacs-lisp
  (use-package avy
    :ensure t
    :bind
    ("M-s" . avy-goto-char))
#+end_src
* Config edit/reload
** Edit
#+begin_src emacs-lisp
  (defun config-visit ()
    (interactive)
    (find-file "~/.emacs.default/config.org"))
  (global-set-key (kbd "C-c e") 'config-visit)
#+end_src
** Reload
#+begin_src emacs-lisp
  (defun config-reload ()
    (interactive)
    (org-babel-load-file (expand-file-name "~/.emacs.default/config.org")))
  (global-set-key (kbd "C-c r") 'config-reload)
#+end_src
* Windows
** switch-window
#+begin_src emacs-lisp
  (use-package switch-window
    :ensure t
    :config
    (setq switch-window-input-style 'minibuffer)
    (setq switch-window-increase 4)
    (setq switch-window-threshold 2)
    (setq switch-window-shortcut-style 'qwerty)
    (setq switch-window-qwerty-shortcuts
	  '("a" "s" "d" "f" "j" "k" "l"))
    :bind
    ([remap other-window] . switch-window))
#+end_src
** Following the window split
#+begin_src emacs-lisp
  (defun split-and-follow-horizontally ()
    (interactive)
    (split-window-below)
    (balance-window)
    (other-window 1))
  (global-set-key (kbd "C-x 2") 'split-and-follow-horizontally)

  (defun split-and-follow-vertically ()
    (interactive)
    (split-window-right)
    (balance-window)
    (other-window 1))
  (global-set-key (kbd "C-x 3") 'split-and-follow-vertically)
#+end_src
* Programming/Code navigation tweaks
** Subword
Navigating through subwords in camelCased words using =M-f= and =M-b= .
#+begin_src emacs-lisp
(global-subword-mode 1)
#+end_src
** Electric
For auto-pairing. (brackets, paranthesis, quotes and all that jazz)
#+begin_src emacs-lisp
  (setq electric-pair-pairs '(
			      (?\{ . ?\})
			      (?\( . ?\))
			      (?\[ . ?\])
			      (?\" . ?\")
			      ))
  (electric-pair-mode t)
#+end_src
** Whole line or region
Kill or save the current line(if no region is selected) or the selected region.
#+begin_src emacs-lisp
  (use-package whole-line-or-region
    :ensure t
    :init (whole-line-or-region-global-mode 1))
#+end_src
** Move line
=M-<arrow-keys>=
#+begin_src emacs-lisp
  (use-package move-text
    :ensure t)
  (move-text-default-bindings)
#+end_src
*** TODO Check about the [[https://github.com/emacsfodder/move-text][github page]] for indentation handling.
** Lines and columns on the modeline
=M-g M-g <number>= is for moving to a line number.
#+begin_src emacs-lisp
  (line-number-mode 1)
  (column-number-mode 1)
#+end_src
** Rainbow
Colors for hex values.
#+begin_src emacs-lisp
  (use-package rainbow-mode
    :ensure t
    :init (rainbow-mode 1))
#+end_src
Coloring the brackets (and other delimiters).
#+begin_src emacs-lisp
  (use-package rainbow-delimiters
    :ensure t
    :init (rainbow-delimiters-mode 1))
#+end_src
** Autocompletion
Using company
#+begin_src emacs-lisp
  (use-package company
    :ensure t
    :init
    (add-hook 'after-init-hook 'global-company-mode))
#+end_src
*** TODO Checkout other auto complete alternatives.
* Dashboard
#+begin_src emacs-lisp
  (use-package dashboard
    :ensure t
    :config
    (dashboard-setup-startup-hook)
    (setq dashboard-items '((recents . 10)))
    (setq dashboard-banner-logo-title "|-Placehoder text-|"))

  (setq initial-buffer-choice (lambda () (get-buffer "*dashboard*")))
#+end_src
** TODO Improve dashboard.
* Modeline
#+begin_src emacs-lisp
  (use-package spaceline
    :ensure t
    :config
    (require 'spaceline-config)
    (setq powerline-default-seperator (quote arrow))
    (spaceline-emacs-theme))
#+end_src
** Hide minor modes
#+begin_src emacs-lisp
  (use-package diminish
    :ensure t
    :init
    (diminish 'beacon-mode)
    (diminish 'subword-mode)
    (diminish 'rainbow-mode)
    (diminish 'which-key-mode)
    (diminish 'whole-line-or-region-local-mode))
#+end_src
** TODO Switch to doom-modeline
* EXWM stuff
** EXWM
#+begin_src emacs-lisp
  (use-package exwm
    :ensure t
    :config
    (require 'exwm-config)
    (exwm-config-default))
#+end_src
*** System tray
#+begin_src emacs-lisp
  (require 'exwm-systemtray)
  (exwm-systemtray-enable)
#+end_src
*** Multi-monitor
#+begin_src emacs-lisp
  (require 'exwm-randr)
  (setq exwm-randr-workspace-output-plist '(1 "eDP1"))
  (add-hook 'exwm-randr-screen-change-hook
	    (lambda ()
	      (start-process-shell-command
	       "xrandr" nil "xrandr --output eDP1 --left-of HDMI1 --auto")))
  (exwm-randr-enable)
#+end_src
** dmenu
#+begin_src emacs-lisp
  (use-package dmenu
    :ensure t
    :bind
    ("s-SPC" . 'dmenu))
#+end_src

* popup-kill-ring
#+begin_src emacs-lisp
  (use-package popup-kill-ring
    :ensure t
    :bind ("M-y" . popup-kill-ring))
#+end_src

